### ISSUE TITLE
Some Metrics Not Exported

### ISSUE THREAD

**Issue by james22402** [Joshi425/minecraft-exporter#6]
Some metrics in Prometheus are not tracked at all even though both the world is mapped and RCON is enabled. I am using a docker compose to bring up both a minecraft server and the exporter. Here is my compose file:
```yml
version: "2.2"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      VERSION: 1.15.2
      TYPE: FORGE
      MEMORY: 6G
      EULA: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "***"
      RCON_PORT: 25575
    ports:
      - 25565:25565
      - 25575:25575
    volumes:
      - server-data:/data
    restart: always

  prometheus-exporter:
    image: theparaguard/minecraft-exporter
    environment:
      RCON_PORT: 25575
      RCON_HOST: 10.0.0.11
      RCON_PASSWORD: "***"
      DYNMAP_ENABLED: "True"
    ports:
      - 8000:8000
    volumes_from:
      - mc:ro
    restart: always
    depends_on:
      mc:
        condition: service_healthy

volumes:
  server-data:
```
As a note, the exporter image I am using is something I tweaked from your image/code. Instead of pumping the world directly into the `/world` folder, I created a higher `/data` folder that contains the `/world` folder.
All I changed were lines `14`, `15`, `16`, `17` in `minecraft-exporter.py` the stats directory was now `/data/world/stats` rather than `/world/stats`.

Regardless, here is an example of what I am seeing as the error:
The metric `overall_ticktime` is tracked but not the `player_online` metric though supposedly they're bundled together. I suspect it might be because I am running a forge world, but your example volume seems to support forge servers so I'm not sure that is the problem. If you need any more information from me let me know.
